name: nuxeo_dart_automation_sandbox
description: A Nuxeo Automation Sandbox in Dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.9.0 <1.0.0'
  js: any
  markdown: any
  nuxeo_automation:
    git: https://github.com/nelsonsilva/nuxeo-dart-automation.git
  polymer: '>=0.9.0 <1.0.0'
  polymer_elements: '>=0.1.1 <1.0.0'
  route: '>=0.4.6 <1.0.0'
transformers:
- polymer:
    entry_points: web/index.html
