name: nuxeo_dart_automation_sandbox
description: A Nuxeo Automation Sandbox in Dart
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <1.0.0'
  js: any
  nuxeo_automation:
    git: https://github.com/nelsonsilva/nuxeo-dart-automation.git
  polymer: '>=0.10.0-pre.7 <0.11.0'
  route_hierarchical: '>=0.4.17 <1.0.0'
transformers:
- polymer:
    entry_points: web/index.html
