name: nuxeo_dart_automation_sandbox
description: A Nuxeo Automation Sandbox in Dart
dependencies:
  browser: any
  js: any
  markdown: any
  nuxeo_automation: #'0.0.1+1'
    path: ../../../../nuxeo-dart-automation
  polymer:
    git:
      ref: polymer
      url: https://github.com/dart-lang/web-ui.git
dev_dependencies:
  hop: '>=0.24.1'
