name: 'nuxeo_api_playground'
description: Nuxeo API Playground
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <1.0.0'
  js: any
  nuxeo_client:
    git: https://github.com/nelsonsilva/nuxeo-dart-client.git
  polymer: '>=0.10.0 <0.12.0'
  polymer_expressions: '>=0.11.0 <0.12.0'
  route_hierarchical: '>=0.4.19 <1.0.0'
dev_dependencies:
  unittest: '>=0.11.0 <1.0.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    - test/test.html
